import React from "react";
import Sections from "@/components/section";
import Head from "next/head";

const about = Sections.about;

type Props = {};

export default function About({}: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <about.Banner />
        <about.AboutUs />
        <about.Reposibilaty />
        <about.FAQ />
      </main>
    </>
  );
}
