import React from "react";
import Sections from "@/components/section";
import Head from "next/head";
import components from "@/components";

type Props = {};

export default function About({}: Props) {
  const about = Sections.about;
  const commonComp = components.common;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <about.Banner /> */}
        <commonComp.PageHeader
          title="О НАС"
          description="Информация о нашей компании, нашей деятельности и услуг"
        />
        <about.AboutUs />
        <about.Reposibilaty />
        <about.FAQ />
      </main>
    </>
  );
}
