import React from "react";
import Components from "@/components";
import Head from "next/head";

type Props = {};

export default function Contact({}: Props) {
  const Sections = Components.section.contact;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sections.ContactBanner />
        <Sections.ContactForm />
      </main>
    </>
  );
}
